# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: planner_message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15planner_message.proto\x12\nplanner_pb\x1a\x1fgoogle/protobuf/timestamp.proto\"z\n\x16PlannerResponseMessage\x12\x33\n\x0ftimestamp_field\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x04path\x18\x02 \x03(\x0b\x32\x1d.planner_pb.Point2DYawMessage\"\xf2\x01\n\x13PlannerInputMessage\x12\x33\n\x0ftimestamp_field\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x05start\x18\x02 \x01(\x0b\x32\x1d.planner_pb.Point2DYawMessage\x12\r\n\x05speed\x18\x03 \x01(\x01\x12(\n\x04goal\x18\x04 \x01(\x0b\x32\x1a.planner_pb.Point2DMessage\x12/\n\nice_pieces\x18\x05 \x03(\x0b\x32\x1b.planner_pb.IcePieceMessage\x12\x0e\n\x06run_id\x18\x06 \x01(\t\"&\n\x0ePoint2DMessage\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\"6\n\x11Point2DYawMessage\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\x0b\n\x03yaw\x18\x03 \x01(\x01\"@\n\x0fIcePieceMessage\x12-\n\tperimeter\x18\x01 \x03(\x0b\x32\x1a.planner_pb.Point2DMessageb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'planner_message_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PLANNERRESPONSEMESSAGE._serialized_start=70
  _PLANNERRESPONSEMESSAGE._serialized_end=192
  _PLANNERINPUTMESSAGE._serialized_start=195
  _PLANNERINPUTMESSAGE._serialized_end=437
  _POINT2DMESSAGE._serialized_start=439
  _POINT2DMESSAGE._serialized_end=477
  _POINT2DYAWMESSAGE._serialized_start=479
  _POINT2DYAWMESSAGE._serialized_end=533
  _ICEPIECEMESSAGE._serialized_start=535
  _ICEPIECEMESSAGE._serialized_end=599
# @@protoc_insertion_point(module_scope)
