#############################################################################
# config for testing planning and path following without physics simulation #
#############################################################################
planner: lattice  # options are lattice, skeleton, straight, default is lattice
max_replan: 1
a_star:
  horizon: 70
  replan: true
  smooth_path:
    add_nodes: 30
    max_dist: 40
  weight: 1.0
costmap:
  m: 76
  n: 12
  alpha: 10
  scale: 4
output_dir: null
plot:
  move_yaxis_threshold: 20
  show: false
  y_axis_limit: 76
prim:
  scale: 4.
  num_headings: 8
  turning_radius: 2.
  step_size: 0.25
ship:
  mass: 1
  padding: 0.25
  vertices: [[1., -0.],
            [0.9, 0.10],
            [0.5, 0.25],
            [-1., 0.25],
            [-1., -0.25],
            [0.5, -0.25],
            [0.9, -0.10]]
sim: false
seed: 1

controller:
  dt: 0.02
  A:
    - [ 0.9909, 0., 0. ]
    - [ 0., 0.9980, 0. ]
    - [ 0., 0., 0.9953 ]
  B: [ 0.04515, 4.321e-5, 1.730e-4 ]
  input_lims: [8.6, 0.5, 0.05]
  Lfc: 0.5
  target_speed: 0.3
  PID_gains:
    - [ 5, 0, 5 ]
    - [ 10, 0, 20 ]
    - [ 10, 0, 20 ]