#############################################################################
# config for testing ship in ice navigation in 2D physics simulation #
#############################################################################
### GLOBAL PARAMS
output_dir: null # 'output/trial0'
comments: ''     # comments about experiment being performed

plot:
  y_axis_limit: 40  # limits the y-axis of the plot
  show: false       # true will show planner plots

### PLANNER PARAMS
#max_replan: 1        # max number of replans
planner: 'lattice'    # options are 'skeleton', 'straight', or 'lattice'
threshold_dist: 0.5   # fraction of path length for deciding whether to update planned path
threshold_cost: 0.95  # fraction of path cost for deciding whether to update planned path
a_star:
  horizon: 20  # receding horizon in metres (needs to be an int for it to be enabled)
  replan: true
  smooth_path:
    add_nodes: 10  # number of nodes to add in node path
    max_dist: 20   # max distance to consider a pair of nodes
  weight: 1        # static weighting for weighed A* f(n) = g(n) + w * h(n) where weight > 1
#  h_baseline: True  # if true, then heuristic is simply euclidean distance to goal
costmap:
  m: 76       # height of ice channel in metres, can set to large number for 'infinite' ice channel
  n: 12       # width of ice channel in metres
  scale: 4    # this gives a resolution of 1/scale x 1/scale metres
  alpha: 10   # collision cost multiplier
prim:
  scale: 4 # Note, there is a limit on how small prim scale can be in relation to costmap scale
  num_headings: 8  # number of headings in the discretized heading space
  step_size: 0.1   # step size for sampling points on the path
  turning_radius: 2.0  # turning radius of the ship in lattice units
ship:
  mass: 1  # mass of ship in kg, should be more realistic...
  padding: 0.25  # adds padding to ship footprint
  vertices: [[1., -0.],
            [0.9, 0.10],
            [0.5, 0.25],
            [-1., 0.25],
            [-1., -0.25],
            [0.5, -0.25],
            [0.9, -0.10]]

### SIMULATION PARAMS
sim:
  t_max: null  # max number of iterations in simulation loop
  steps: 10    # number of simulation steps per iteration
  gravity: !!python/tuple
    - 0
    - 0
  iterations: 10  # controls accuracy of pymunk solver i.e. simulation accuracy, default is 10
  damping: 0      # damping to body velocities
  obstacle_density: 1
obstacle:
  num_obs: 50  # number of random ice obstacles (new pieces are generated to maintain number if inf_stream=True)
  min_r: 2
  max_r: 8
  min_x: 0
  max_x: 40
  min_y: 10
  max_y: 150
anim:
  save: false               # if true save to disk animation plots
  show: true                # if true show animation plots
  plot_steps: 10            # steps between plot updates
  plan_steps: 10            # steps between obstacle and planner updates
  inf_stream: false         # if true then infinite obstacle stream mode is enabled
  move_yaxis_threshold: 10  # distance traveled before y-axis moves
#  new_obs_dist: 50          # distance traveled before new obstacles are added
seed: 1
#ice_current: [0, -1]       # option to add ice current to simulation

### SHIP MODEL AND CONTROLLER PARAMS
controller:
  dt: 0.02  # the ship dynamics model was discretized with this dt
  # States: [r, u, v] : yaw rate (deg/s), surge velocity (m/s), sway velocity (m/s)
  A:
    - [ 0.9909, 0., 0. ]
    - [ 0., 0.9980, 0. ]
    - [ 0., 0., 0.9953 ]
  # Input matrix: differential fore/aft (rps), side tunnel (rps), main prop (rps) (Assume pure motions)
  B: [ 0.04515, 4.321e-5, 1.730e-4 ]
  # Input limits
  # To calculate yaw rate given min turn radius r and surge velocity v
  # 360 / ((2 pi r) / v)
  input_lims: [8.6, 0.5, 0.05]
  # look ahead distance
  Lfc: 0.5
  # target speed
  target_speed: 0.3  # m/s
  PID_gains:  # gains for 3 PIDs
    - [ 5, 0, 5 ]
    - [ 10, 0, 20 ]
    - [ 10, 0, 20 ]
